#!/bin/bash
# TOMCAT.SH
#Steps for Installing tomcat9 on rhe17&8
# install Java JDK 1.8+ as a pre-requisit for tomcat to run.
# https://github.com/UTONWA123/package-management/tree/main/Tomcat-installation
cd /opt
sudo yum install git wget -y

sudo yum install java-21.0.11-openjdk-devel -y

# Download tomcat software and extract it.
sudo yum install wget unzip -y

# download and extract tomcat software.
sudo wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.22/bin/apache-tomcat-11.0.22.tar.gz
sudo tar -xvf apache-tomcat-11.0.22.tar.gz
sudo rm apache-tomcat-11.0.22.tar.gz

sudo chomd 777 -R /opt/tomcat11
sudo sh /opt/tomcat/bin/startup.sh
# create a soft link to start and stop tomcat from anywhere
sudo ln -s /opt/tomcat/bin/startup.sh /usr/bin/starttomcat
sudo ln -s /opt/tomcat/bin/shutdown.sh /usr/bin/stoptomcat
sudo starttomcat
echo "end on tomcat installation"
#=========

#2. start of tomcat configuration


#Tomcat server configuration:
find / -name server.xml context.xml
vim /opt/tomcat9/conf/server.xml
vim /opt/tomcat9/webapps/manager/META-INF/context.xml
vi /opt/tomcat9/conf/tomcat-user.xml  # to add user

       <user username="Utonwa" password="admin"roles="manager-gui,admin-gui"/>


/opt/tomcat9/conf/context.xml

vi /opt/tomcat9/webapps/manager/META-INF/context.xml

  vi /opt/tomcat9/conf/tomcat-user.xml  # to add user


            username Yourname password=password   roles=manager-gui
